//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace examentp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class carte
    {
        public int code_carte { get; set; }
        public int code_client { get; set; }
        public int num_carte { get; set; }
        public string date_exp { get; set; }
    
        public virtual compte compte { get; set; }
    }
}
